name: Delivery

on:
  release:
    types: [released, prereleased]

jobs:
  test:
    uses: ./.github/workflows/integration.yml

  dockerize-staging:
    if: ${{ github.event.release.prerelease }}
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          build-args: CONFIGURATION=staging
          push: true
          tags: |
            roithme0/kochwiki-frontend:alpha
          cache-from: type=gha
          cache-to: type=gha,mode=max

  dockerize-production:
    if: ${{ !github.event.release.prerelease }}
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          build-args: CONFIGURATION=production
          push: true
          tags: |
            roithme0/kochwiki-frontend:latest
            roithme0/kochwiki-frontend:${{github.event.release.tag_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
